// ============================================================
// EXPORT — Markdown, DOCX, PPTX, Copy-to-clipboard
// ============================================================

/**
 * Generate a Markdown validation annotation for a given section/index/field.
 * Returns a blockquote line (e.g. "> ⚠️ **uncertain:** ...") or empty string.
 */
function formatMdValidation(section, index, field, featureIndex) {
  if (typeof getValidationStatus === 'undefined') return '';
  const status = (featureIndex != null)
    ? getValidationStatus(section, index, field, featureIndex)
    : getValidationStatus(section, index, field);
  const detail = (typeof getValidationDetail !== 'undefined')
    ? ((featureIndex != null)
        ? getValidationDetail(section, index, field, featureIndex)
        : getValidationDetail(section, index, field))
    : null;
  if (!status) return '';

  if (status === 'likely_valid') return '> ✅ Source confirmed';
  const icon = status === 'uncertain' ? '⚠️' : '❌';
  const label = status === 'uncertain' ? 'uncertain' : 'flagged';
  let line = '> ' + icon + ' **' + label + ':** ' + (detail?.reason || '');
  if (detail?.suggested_fix) line += ' *→ ' + detail.suggested_fix + '*';
  return line;
}

/**
 * Generate a plain-text validation annotation for PPTX table cells.
 * Returns a newline-prefixed string or empty string.
 */
function pptxValidationText(section, index, field, featureIndex) {
  if (typeof getValidationStatus === 'undefined') return '';
  const status = (featureIndex != null)
    ? getValidationStatus(section, index, field, featureIndex)
    : getValidationStatus(section, index, field);
  const detail = (typeof getValidationDetail !== 'undefined')
    ? ((featureIndex != null)
        ? getValidationDetail(section, index, field, featureIndex)
        : getValidationDetail(section, index, field))
    : null;
  if (!status) return '';

  if (status === 'likely_valid') return '\n✅ confirmed';
  const icon = status === 'uncertain' ? '⚠️' : '❌';
  let text = '\n' + icon + ' ' + (detail?.reason || '');
  if (detail?.suggested_fix) text += '\n→ ' + detail.suggested_fix;
  return text;
}

/**
 * Build a combined Markdown document from both stages.
 */
function buildMarkdown(stage1, stage2, projectSlug) {
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10);
  const lines = [];

  lines.push('# Innovative Ideation Scan: ' + (projectSlug || 'Untitled'));
  lines.push('**Date:** ' + dateStr);
  lines.push('**Generated by:** AI Ideation Scanner (SDC AI Tools)');
  lines.push('**Status:** DRAFT — requires practitioner review before use');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── PART 1: Innovation Scan Insights ──
  lines.push('## Part 1: Innovation Scan Insights');
  lines.push('');
  lines.push('### Scan Summary');
  lines.push(stage1.scan_summary || '_No summary provided._');
  lines.push('');

  // Best Practices
  lines.push('### Best Practices');
  lines.push('');
  if (stage1.best_practices && stage1.best_practices.length > 0) {
    stage1.best_practices.forEach((bp, i) => {
      lines.push('#### ' + (i + 1) + '. ' + bp.title);
      const titleVal = formatMdValidation('best_practices', i, 'title');
      if (titleVal) lines.push(titleVal);
      lines.push('**Source:** ' + (bp.source_domain || 'N/A'));
      lines.push('');
      lines.push(bp.description || '');
      lines.push('');
      lines.push('**Relevance:** ' + (bp.relevance || 'N/A'));
      if (bp.url_hint) {
        lines.push('**Reference:** ' + formatMdLink(bp.url_hint));
        const urlVal = formatMdValidation('best_practices', i, 'url_hint');
        if (urlVal) lines.push(urlVal);
      }
      lines.push('');
    });
  } else {
    lines.push('_No best practices identified._');
    lines.push('');
  }

  // Analogous Solutions
  lines.push('### Analogous Solutions');
  lines.push('');
  if (stage1.analogous_solutions && stage1.analogous_solutions.length > 0) {
    stage1.analogous_solutions.forEach((as, i) => {
      lines.push('#### ' + (i + 1) + '. ' + as.title);
      const titleVal = formatMdValidation('analogous_solutions', i, 'title');
      if (titleVal) lines.push(titleVal);
      lines.push('**Sector:** ' + (as.sector || 'N/A'));
      lines.push('');
      lines.push(as.description || '');
      lines.push('');
      lines.push('**Transferable Insight:** ' + (as.transferable_insight || 'N/A'));
      if (as.url_hint) {
        lines.push('**Reference:** ' + formatMdLink(as.url_hint));
        const urlVal = formatMdValidation('analogous_solutions', i, 'url_hint');
        if (urlVal) lines.push(urlVal);
      }
      lines.push('');
    });
  } else {
    lines.push('_No analogous solutions identified._');
    lines.push('');
  }

  // Design Trends
  lines.push('### Design Trends');
  lines.push('');
  if (stage1.design_trends && stage1.design_trends.length > 0) {
    stage1.design_trends.forEach((dt, i) => {
      lines.push('**' + (i + 1) + '. ' + dt.trend + '** — ' + (dt.description || ''));
      const trendTitleVal = formatMdValidation('design_trends', i, 'title');
      if (trendTitleVal) lines.push(trendTitleVal);
      lines.push('*Application:* ' + (dt.application || 'N/A'));
      if (dt.url_hint) {
        lines.push('*Reference:* ' + formatMdLink(dt.url_hint));
        const urlVal = formatMdValidation('design_trends', i, 'url_hint');
        if (urlVal) lines.push(urlVal);
      }
      lines.push('');
    });
  } else {
    lines.push('_No design trends identified._');
    lines.push('');
  }

  // Inspiration Sources
  lines.push('### Inspiration Sources');
  lines.push('');
  if (stage1.inspiration_sources && stage1.inspiration_sources.length > 0) {
    stage1.inspiration_sources.forEach((is, i) => {
      let line = '- **' + is.name + '** (' + (is.type || 'Resource') + ') — ' + (is.why_relevant || '');
      if (is.url_hint) line += ' · ' + formatMdLink(is.url_hint);
      lines.push(line);
      const nameVal = formatMdValidation('inspiration_sources', i, 'title');
      if (nameVal) lines.push('  ' + nameVal);
      if (is.url_hint) {
        const urlVal = formatMdValidation('inspiration_sources', i, 'url_hint');
        if (urlVal) lines.push('  ' + urlVal);
      }
    });
    lines.push('');
  } else {
    lines.push('_No inspiration sources identified._');
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ── PART 2: Unpacked Solution Concepts ──
  lines.push('## Part 2: Unpacked Solution Concepts');
  lines.push('');
  lines.push('### Solution Overview');
  lines.push(stage2.solution_overview || '_No overview provided._');
  lines.push('');

  // Solution Concepts
  if (stage2.solution_concepts && stage2.solution_concepts.length > 0) {
    stage2.solution_concepts.forEach((concept, ci) => {
      lines.push('### Concept ' + (ci + 1) + ': ' + concept.concept_name);
      const conceptTitleVal = formatMdValidation('solution_concepts', ci, 'title');
      if (conceptTitleVal) lines.push(conceptTitleVal);
      if (concept.opportunity_source) {
        lines.push('**Opportunity:** ' + concept.opportunity_source);
      }
      lines.push('');
      lines.push(concept.concept_description || '');
      lines.push('');

      if (concept.features && concept.features.length > 0) {
        lines.push('| # | Feature | Description | HCD Value | Best Practice Ref | Complexity |');
        lines.push('|---|---------|-------------|-----------|-------------------|------------|');
        const featureValNotes = [];
        concept.features.forEach((f, fi) => {
          const desc = (f.description || '').replace(/\n/g, ' ').replace(/\|/g, '\\|');
          const hcd = (f.hcd_value_proposition || '').replace(/\n/g, ' ').replace(/\|/g, '\\|');
          let ref = (f.best_practice_reference || '').replace(/\n/g, ' ').replace(/\|/g, '\\|');
          if (f.best_practice_url) {
            ref += ' (' + formatMdLink(f.best_practice_url).replace(/\|/g, '\\|') + ')';
          }
          const cx = f.implementation_complexity || 'N/A';
          lines.push('| ' + (fi + 1) + ' | **' + (f.feature_name || '') + '** | ' + desc + ' | ' + hcd + ' | ' + ref + ' | ' + cx + ' |');
          // Collect validation notes for features (can't embed in table cells)
          if (f.best_practice_url) {
            const fVal = formatMdValidation('solution_concepts', ci, 'best_practice_url', fi);
            if (fVal) featureValNotes.push('- **' + (f.feature_name || 'Feature ' + (fi + 1)) + ':** ' + fVal.replace(/^> /, ''));
          }
        });
        lines.push('');
        // Append feature validation notes after the table
        if (featureValNotes.length > 0) {
          lines.push('**Source Validation Notes:**');
          featureValNotes.forEach(n => lines.push(n));
          lines.push('');
        }
      }
    });
  }

  // Cross-Cutting Themes
  if (stage2.cross_cutting_themes && stage2.cross_cutting_themes.length > 0) {
    lines.push('### Cross-Cutting Themes');
    lines.push('');
    stage2.cross_cutting_themes.forEach((t, i) => {
      let line = '- **' + t.theme + ':** ' + (t.description || '');
      if (t.url_hint) line += ' · ' + formatMdLink(t.url_hint);
      lines.push(line);
      const themeVal = formatMdValidation('cross_cutting_themes', i, 'title');
      if (themeVal) lines.push('  ' + themeVal);
      if (t.url_hint) {
        const urlVal = formatMdValidation('cross_cutting_themes', i, 'url_hint');
        if (urlVal) lines.push('  ' + urlVal);
      }
    });
    lines.push('');
  }

  // Risks & Considerations
  if (stage2.risks_and_considerations && stage2.risks_and_considerations.length > 0) {
    lines.push('### Risks & Considerations');
    lines.push('');
    lines.push('| Risk | Mitigation |');
    lines.push('|------|------------|');
    stage2.risks_and_considerations.forEach((r) => {
      const risk = (r.risk || '').replace(/\|/g, '\\|');
      const mit = (r.mitigation || '').replace(/\|/g, '\\|');
      lines.push('| ' + risk + ' | ' + mit + ' |');
    });
    lines.push('');
  }

  // ── Source Validation Summary (if validation has been run) ──
  if (typeof lastValidation !== 'undefined' && lastValidation && lastValidation.flags) {
    lines.push('### Source Validation Summary');
    lines.push('');
    const flags = lastValidation.flags;
    const valid = flags.filter(f => f.status === 'likely_valid').length;
    const uncertain = flags.filter(f => f.status === 'uncertain').length;
    const invalid = flags.filter(f => f.status === 'likely_invalid').length;
    const score = lastValidation.confidence_score != null
      ? Math.round(lastValidation.confidence_score * 100) : null;
    lines.push('- ✅ ' + valid + ' confirmed · ⚠️ ' + uncertain + ' uncertain · ❌ ' + invalid + ' flagged');
    if (score !== null) lines.push('- **Confidence:** ' + score + '%');
    if (lastValidation.validation_summary) {
      lines.push('');
      lines.push(lastValidation.validation_summary);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*AI-generated ideation scan. Practitioner review required before use in deliverables.*');

  return lines.join('\n');
}

/**
 * Format a url_hint as a Markdown link.
 * If it starts with http(s), render as [url](url).
 * Otherwise, render as a Google search link.
 */
function formatMdLink(urlHint) {
  if (!urlHint) return '';
  if (/^https?:\/\//i.test(urlHint)) {
    return '[' + urlHint + '](' + urlHint + ')';
  }
  const searchUrl = 'https://www.google.com/search?q=' + encodeURIComponent(urlHint);
  return '[🔎 ' + urlHint + '](' + searchUrl + ')';
}

/**
 * Download a Markdown file.
 */
function exportMarkdown(stage1, stage2, projectSlug) {
  const md = buildMarkdown(stage1, stage2, projectSlug);
  const dateStr = new Date().toISOString().slice(0, 10);
  const slug = (projectSlug || 'ideation-scan').replace(/\s+/g, '-').toLowerCase();
  const filename = dateStr + '-ideation-scan-' + slug + '.md';

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  downloadBlob(blob, filename);
}

/**
 * Download a DOCX file (Markdown → HTML → DOCX).
 */
function exportDocx(stage1, stage2, projectSlug) {
  const md = buildMarkdown(stage1, stage2, projectSlug);
  const dateStr = new Date().toISOString().slice(0, 10);
  const slug = (projectSlug || 'ideation-scan').replace(/\s+/g, '-').toLowerCase();
  const filename = dateStr + '-ideation-scan-' + slug + '.docx';

  // Convert markdown to HTML
  const html = typeof marked !== 'undefined'
    ? marked.parse(md)
    : '<pre>' + md.replace(/</g, '&lt;') + '</pre>';

  // Wrap in a basic document structure
  const fullHtml = '<!DOCTYPE html><html><head><meta charset="utf-8"><style>'
    + 'body{font-family:Calibri,sans-serif;font-size:11pt;line-height:1.5;}'
    + 'h1{font-size:18pt;color:#1a3a5c;} h2{font-size:14pt;color:#1a3a5c;} h3{font-size:12pt;color:#1a3a5c;}'
    + 'table{border-collapse:collapse;width:100%;margin:12px 0;} th,td{border:1px solid #d1d5db;padding:6px 10px;font-size:10pt;text-align:left;}'
    + 'th{background:#f3f4f6;font-weight:600;}'
    + 'a{color:#4A90D9;text-decoration:underline;}'
    + '</style></head><body>' + html + '</body></html>';

  if (typeof htmlDocx !== 'undefined') {
    const blob = htmlDocx.asBlob(fullHtml);
    downloadBlob(blob, filename);
  } else {
    // Fallback: download as HTML
    const blob = new Blob([fullHtml], { type: 'text/html;charset=utf-8' });
    downloadBlob(blob, filename.replace('.docx', '.html'));
  }
}

/**
 * Download a PPTX file.
 */
function exportPptx(stage1, stage2, projectSlug) {
  if (typeof PptxGenJS === 'undefined') {
    alert('PptxGenJS library not loaded. PPTX export is unavailable.');
    return;
  }

  const pptx = new PptxGenJS();
  const dateStr = new Date().toISOString().slice(0, 10);
  const slug = (projectSlug || 'ideation-scan').replace(/\s+/g, '-').toLowerCase();

  // Colour constants
  const NAVY = '1a3a5c';
  const BLUE = '4A90D9';
  const WHITE = 'FFFFFF';
  const GREY = '6b7280';
  const GREEN = '2f9e44';
  const AMBER = 'e67700';
  const RED = 'c92a2a';

  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'SDC AI Tools';
  pptx.subject = 'Innovative Ideation Scan';

  // ── Slide 1: Title ──
  const s1 = pptx.addSlide();
  s1.background = { color: NAVY };
  s1.addText('Innovative Ideation Scan', { x: 0.8, y: 1.5, w: 11, h: 1.2, fontSize: 32, color: WHITE, bold: true });
  s1.addText(projectSlug || 'Untitled Project', { x: 0.8, y: 2.7, w: 11, h: 0.8, fontSize: 20, color: BLUE });
  s1.addText(dateStr + '  •  AI-generated — practitioner review required', { x: 0.8, y: 4.5, w: 11, h: 0.5, fontSize: 12, color: GREY });

  // ── Slide 2: Innovation Scan Summary ──
  const s2 = pptx.addSlide();
  s2.addText('Innovation Scan Summary', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, color: NAVY, bold: true });
  s2.addText(stage1.scan_summary || 'No summary provided.', { x: 0.5, y: 1.1, w: 12, h: 1.2, fontSize: 14, color: '374151', wrap: true });

  // Best practices summary
  if (stage1.best_practices && stage1.best_practices.length > 0) {
    const bpRows = [
      [{ text: 'Best Practice', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
       { text: 'Source', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
       { text: 'Relevance', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
       { text: 'Reference', options: { bold: true, color: WHITE, fill: { color: NAVY } } }]
    ];
    stage1.best_practices.slice(0, 6).forEach((bp, i) => {
      const titleValText = pptxValidationText('best_practices', i, 'title');
      const valText = pptxValidationText('best_practices', i, 'url_hint');
      bpRows.push([(bp.title || '') + titleValText, bp.source_domain || '', bp.relevance || '', (bp.url_hint || '') + valText]);
    });
    s2.addTable(bpRows, { x: 0.5, y: 2.5, w: 12, colW: [3, 2, 4.5, 2.5], fontSize: 9, border: { pt: 0.5, color: 'd1d5db' }, autoPage: true });
  }

  // ── Slide 3: Analogous Solutions & Trends ──
  const s3 = pptx.addSlide();
  s3.addText('Analogous Solutions & Design Trends', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, color: NAVY, bold: true });

  if (stage1.analogous_solutions && stage1.analogous_solutions.length > 0) {
    const asRows = [
      [{ text: 'Solution', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
       { text: 'Sector', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
       { text: 'Transferable Insight', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
       { text: 'Reference', options: { bold: true, color: WHITE, fill: { color: NAVY } } }]
    ];
    stage1.analogous_solutions.slice(0, 5).forEach((as, i) => {
      const titleValText = pptxValidationText('analogous_solutions', i, 'title');
      const valText = pptxValidationText('analogous_solutions', i, 'url_hint');
      asRows.push([(as.title || '') + titleValText, as.sector || '', as.transferable_insight || '', (as.url_hint || '') + valText]);
    });
    s3.addTable(asRows, { x: 0.5, y: 1.0, w: 12, colW: [2.5, 1.5, 5.5, 2.5], fontSize: 9, border: { pt: 0.5, color: 'd1d5db' } });
  }

  if (stage1.design_trends && stage1.design_trends.length > 0) {
    const dtY = 1.0 + (stage1.analogous_solutions?.length || 0) * 0.45 + 1.2;
    const dtRows = [
      [{ text: 'Trend', options: { bold: true, color: WHITE, fill: { color: BLUE } } },
       { text: 'Application', options: { bold: true, color: WHITE, fill: { color: BLUE } } },
       { text: 'Reference', options: { bold: true, color: WHITE, fill: { color: BLUE } } }]
    ];
    stage1.design_trends.slice(0, 5).forEach((dt, i) => {
      const trendTitleValText = pptxValidationText('design_trends', i, 'title');
      const valText = pptxValidationText('design_trends', i, 'url_hint');
      dtRows.push([(dt.trend || '') + trendTitleValText, dt.application || '', (dt.url_hint || '') + valText]);
    });
    s3.addTable(dtRows, { x: 0.5, y: Math.min(dtY, 4.0), w: 12, colW: [3, 6.5, 2.5], fontSize: 9, border: { pt: 0.5, color: 'd1d5db' } });
  }

  // ── Slide 4: Solution Overview ──
  const s4 = pptx.addSlide();
  s4.addText('Solution Overview', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, color: NAVY, bold: true });
  s4.addText(stage2.solution_overview || 'No overview provided.', { x: 0.5, y: 1.1, w: 12, h: 1.5, fontSize: 14, color: '374151', wrap: true });

  // Concept summary list
  if (stage2.solution_concepts && stage2.solution_concepts.length > 0) {
    const conceptList = stage2.solution_concepts.map((c, i) =>
      (i + 1) + '. ' + c.concept_name + ' (' + (c.features?.length || 0) + ' features)'
    ).join('\n');
    s4.addText(conceptList, { x: 0.5, y: 3.0, w: 12, h: 3, fontSize: 13, color: '374151', wrap: true, bullet: false });
  }

  // ── Slides 5+: One per solution concept ──
  if (stage2.solution_concepts) {
    stage2.solution_concepts.forEach((concept, ci) => {
      const cs = pptx.addSlide();
      cs.addText('Concept ' + (ci + 1) + ': ' + concept.concept_name, { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 20, color: NAVY, bold: true });
      cs.addText(concept.concept_description || '', { x: 0.5, y: 1.0, w: 12, h: 1.0, fontSize: 11, color: '374151', wrap: true });

      if (concept.features && concept.features.length > 0) {
        const fRows = [
          [{ text: 'Feature', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
           { text: 'HCD Value', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
           { text: 'Best Practice Ref', options: { bold: true, color: WHITE, fill: { color: NAVY } } },
           { text: 'Complexity', options: { bold: true, color: WHITE, fill: { color: NAVY } } }]
        ];
        concept.features.forEach((f, fi) => {
          const cxColor = f.implementation_complexity === 'Low' ? GREEN
            : f.implementation_complexity === 'High' ? RED : AMBER;
          const valText = f.best_practice_url ? pptxValidationText('solution_concepts', ci, 'best_practice_url', fi) : '';
          const refText = (f.best_practice_reference || '')
            + (f.best_practice_url ? '\n' + f.best_practice_url : '')
            + valText;
          fRows.push([
            f.feature_name || '',
            f.hcd_value_proposition || '',
            refText,
            { text: f.implementation_complexity || 'N/A', options: { color: cxColor, bold: true } }
          ]);
        });
        cs.addTable(fRows, { x: 0.5, y: 2.2, w: 12, colW: [2.5, 3.5, 4, 2], fontSize: 9, border: { pt: 0.5, color: 'd1d5db' }, autoPage: true });
      }
    });
  }

  // ── Cross-Cutting Themes slide ──
  if (stage2.cross_cutting_themes && stage2.cross_cutting_themes.length > 0) {
    const ts = pptx.addSlide();
    ts.addText('Cross-Cutting Themes', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, color: NAVY, bold: true });
    const tRows = [
      [{ text: 'Theme', options: { bold: true, color: WHITE, fill: { color: BLUE } } },
       { text: 'Description', options: { bold: true, color: WHITE, fill: { color: BLUE } } },
       { text: 'Reference', options: { bold: true, color: WHITE, fill: { color: BLUE } } }]
    ];
    stage2.cross_cutting_themes.forEach((t, i) => {
      const themeValText = pptxValidationText('cross_cutting_themes', i, 'title');
      const valText = t.url_hint ? pptxValidationText('cross_cutting_themes', i, 'url_hint') : '';
      tRows.push([(t.theme || '') + themeValText, t.description || '', (t.url_hint || '') + valText]);
    });
    ts.addTable(tRows, { x: 0.5, y: 1.1, w: 12, colW: [3, 6.5, 2.5], fontSize: 10, border: { pt: 0.5, color: 'd1d5db' } });
  }

  // ── Final slide: Risks ──
  if (stage2.risks_and_considerations && stage2.risks_and_considerations.length > 0) {
    const rs = pptx.addSlide();
    rs.addText('Risks & Considerations', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, color: NAVY, bold: true });
    const rRows = [
      [{ text: 'Risk', options: { bold: true, color: WHITE, fill: { color: RED } } },
       { text: 'Mitigation', options: { bold: true, color: WHITE, fill: { color: GREEN } } }]
    ];
    stage2.risks_and_considerations.forEach(r => {
      rRows.push([r.risk || '', r.mitigation || '']);
    });
    rs.addTable(rRows, { x: 0.5, y: 1.1, w: 12, colW: [5, 7], fontSize: 10, border: { pt: 0.5, color: 'd1d5db' } });
  }

  // ── Source Validation Summary slide (if validation has been run) ──
  if (typeof lastValidation !== 'undefined' && lastValidation && lastValidation.flags) {
    const vs = pptx.addSlide();
    vs.addText('Source Validation Summary', { x: 0.5, y: 0.3, w: 12, h: 0.6, fontSize: 22, color: NAVY, bold: true });

    const flags = lastValidation.flags;
    const valid = flags.filter(f => f.status === 'likely_valid').length;
    const uncertain = flags.filter(f => f.status === 'uncertain').length;
    const invalid = flags.filter(f => f.status === 'likely_invalid').length;
    const total = flags.length;
    const score = lastValidation.confidence_score != null
      ? Math.round(lastValidation.confidence_score * 100) : null;

    let summaryText = '✅ ' + valid + ' confirmed  ·  ⚠️ ' + uncertain + ' uncertain  ·  ❌ ' + invalid + ' flagged  ·  ' + total + ' total checked';
    if (score !== null) summaryText += '  ·  Confidence: ' + score + '%';
    vs.addText(summaryText, { x: 0.5, y: 1.1, w: 12, h: 0.5, fontSize: 14, color: '374151', wrap: true });

    if (lastValidation.validation_summary) {
      vs.addText(lastValidation.validation_summary, { x: 0.5, y: 1.8, w: 12, h: 1.5, fontSize: 11, color: '6b7280', wrap: true });
    }
  }

  // Save
  const filename = dateStr + '-ideation-scan-' + slug + '.pptx';
  pptx.writeFile({ fileName: filename });
}

/**
 * Copy Markdown to clipboard.
 */
async function copyToClipboard(stage1, stage2, projectSlug) {
  const md = buildMarkdown(stage1, stage2, projectSlug);
  try {
    await navigator.clipboard.writeText(md);
    showToast('Copied to clipboard!');
  } catch (e) {
    // Fallback for older browsers
    const ta = document.createElement('textarea');
    ta.value = md;
    ta.style.position = 'fixed';
    ta.style.left = '-9999px';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    showToast('Copied to clipboard!');
  }
}

/**
 * Helper: trigger a file download from a Blob.
 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}

// ============================================================
// JSON SAVE / LOAD TEMPLATES
// ============================================================

/**
 * Build a JSON template containing all inputs and results.
 * This allows saving and restoring a complete ideation scan session.
 */
function buildJsonTemplate(projectSlug, lastResult) {
  const context = (document.getElementById('project-context')?.value || '').trim();
  const opportunities = (document.getElementById('opportunities-text')?.value || '').trim();
  const scanFocus = document.getElementById('scan-focus')?.value || 'all';
  const otherFocusText = (document.getElementById('other-focus-text')?.value || '').trim();

  const template = {
    _tool: 'SDC Ideation Scanner',
    _version: '2.1',
    savedAt: new Date().toISOString(),
    projectSlug: projectSlug || '',
    projectContext: context,
    opportunitiesText: opportunities,
    scanFocus: scanFocus,
    otherFocusText: otherFocusText,
    uploadedFileNames: (typeof uploadedFiles !== 'undefined' ? uploadedFiles : []).map(f => f.name),
  };

  // Include results if a scan has been run
  if (lastResult) {
    template.results = {
      stage1: lastResult.stage1 || null,
      stage2: lastResult.stage2 || null,
      model: lastResult.model || '',
      elapsed: lastResult.elapsed || '',
      usage: lastResult.usage || null,
    };

    // Include validation token usage if available
    if (typeof cumulativeUsage !== 'undefined' && cumulativeUsage && cumulativeUsage.validationTokens) {
      template.results.validationUsage = cumulativeUsage.validationTokens;
    }
  }

  // Include validation results if validation has been run
  if (typeof lastValidation !== 'undefined' && lastValidation) {
    template.validation = lastValidation;
  }
  if (typeof validationMap !== 'undefined' && Object.keys(validationMap).length > 0) {
    template.validationMap = validationMap;
  }

  return template;
}

/**
 * Export the current session as a JSON file.
 */
function exportJSON(projectSlug, lastResult) {
  const template = buildJsonTemplate(projectSlug, lastResult);
  const dateStr = new Date().toISOString().slice(0, 10);
  const hh = String(new Date().getHours()).padStart(2, '0');
  const mm = String(new Date().getMinutes()).padStart(2, '0');
  const slug = (projectSlug || 'ideation-scan').replace(/\s+/g, '-').toLowerCase();
  const filename = 'ideation-scan-' + slug + '-' + dateStr + '-' + hh + mm + '.json';

  const blob = new Blob([JSON.stringify(template, null, 2)], { type: 'application/json' });
  downloadBlob(blob, filename);
  showToast('💾 Saved ' + filename);
}

/**
 * Import a JSON template file and restore the session.
 * @param {File} file - The JSON file to import
 * @param {function} onComplete - Callback with the parsed template
 */
function importJSON(file, onComplete) {
  if (!file || !file.name.endsWith('.json')) {
    showToast('❌ Please select a .json file exported from this tool.');
    return;
  }

  const reader = new FileReader();
  reader.onload = (ev) => {
    try {
      const parsed = JSON.parse(ev.target.result);

      // Basic validation — check it's from this tool
      if (parsed._tool && parsed._tool !== 'SDC Ideation Scanner') {
        showToast('⚠ This JSON file is from "' + parsed._tool + '", not the Ideation Scanner.');
        return;
      }

      if (onComplete) onComplete(parsed);
    } catch (err) {
      console.error('JSON import error:', err);
      showToast('❌ Could not parse JSON file: ' + err.message);
    }
  };
  reader.onerror = () => showToast('❌ Could not read file.');
  reader.readAsText(file);
}

/**
 * Show a toast notification.
 */
function showToast(message) {
  let toast = document.getElementById('toast');
  if (!toast) {
    toast = document.createElement('div');
    toast.id = 'toast';
    toast.className = 'toast';
    document.body.appendChild(toast);
  }
  toast.textContent = message;
  toast.classList.add('show');
  setTimeout(() => toast.classList.remove('show'), 2500);
}
